version: 2
jobs:
  release:
    docker:
      - image: gesquive/docker-builder:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
      - run: docker info
      - run: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: make release-multiarch


workflows:
  version: 2
  build-workflow:
    jobs:
      - release:
          context: docker-deploy

# TODO: get this to build weekly so tz and ca-certs are up to date
# TODO: tag with build date
